Support pool refresh
elsid/resource_pool pull request #24
Opened 2020-04-28 21:01 UTC by elsid

Force pool handles to be wasted. Available will be wasted on the method call. Used will be wasted on the next recycle.

2020-04-29 20:04 UTC, thed636 requested changes

2020-04-29 20:04 UTC, thed636 commented on include/yamail/resource_pool/async/detail/pool_impl.hpp
> +    void refresh();
I’d propose something like `invalidate` or `waste` instead of `refresh` because no refresh made bu this method.

2020-04-30 18:47 UTC, elsid commented
Codecov [doesn't work properly](https://codecov.io/gh/elsid/resource_pool/compare/6a4074465cc672fc1999035ef3e851d7c250134c...50bd4a52bddc9a0f1aa4f5051860ea45a4d3c2e7/src/include/yamail/resource_pool/detail/storage.hpp) gcov shows different coverage.
![Screenshot from 2020-04-30 20-43-52](https://user-images.githubusercontent.com/764107/80747315-8b92ee80-8b23-11ea-9b2c-7bee9065c38b.png)

2020-04-30 18:49 UTC, elsid commented on include/yamail/resource_pool/async/detail/pool_impl.hpp
> +    void refresh();
Done.

2020-04-30 20:15 UTC, thed636 approved these changes

2020-04-30 21:45 UTC, merged